<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>GHANTOM.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Conversation\script.json" />
  </ItemGroup>

</Project>
